# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('locked', models.BooleanField(default=False)),
                ('config', models.TextField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
